name: viju_mobile_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  modal_bottom_sheet: ^3.0.0-pre
  equatable: ^2.0.5
  dio: ^5.0.1
  flutter_pretty_dio_logger: ^3.0.0
  flutter_bloc: ^8.1.2
  no_context_navigation: ^2.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  validators: ^3.0.0
  bloc_concurrency: ^0.2.1
  intl: ^0.18.0
  flutter_staggered_animations: ^1.1.1
  flutter_dotenv: ^5.1.0
  adaptive_theme: ^3.2.1
  shared_preferences: ^2.2.0
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: 'Poppins'
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
