name: viju_mobile_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.2+5

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.4.0
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.0.4
  flutter_localization: ^0.1.14
  flutter_secure_storage: ^8.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  flutter_timeline:
    git:
      url: https://github.com/nashihu/flutter-timeline.git
      ref: main
  flutter_web_browser: ^0.17.1
  flutterfire_cli: ^0.3.0-dev.18
  freezed_annotation: ^2.2.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  json_annotation: ^4.8.0
  logger: ^1.4.0
  modal_bottom_sheet: ^3.0.0-pre
  no_context_navigation: ^2.1.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  validators: ^3.0.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo/app_logo_ios.jpg"
  image_path_android: "assets/logo/app_logo.jpg"
  adaptive_icon_background: "assets/logo/background.png"
  adaptive_icon_foreground: "assets/logo/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: "Poppins"
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
